# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-03 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='quantity',
            new_name='pledge',
        ),
    ]
