# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-22 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('bug_or_feature', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature')], max_length=50)),
                ('upvotes', models.IntegerField(default=0)),
                ('pledge', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('to do', 'To Do'), ('working on it', 'Working on it'), ('complete', 'Complete')], default='to do', max_length=200)),
                ('userID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('bugID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.Bug')),
                ('userID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
